# Generated by Django 3.2.6 on 2021-08-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferApp', '0002_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='transfer_From',
            field=models.BigIntegerField(default=1),
        ),
    ]
