# Generated by Django 3.2.6 on 2021-08-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferApp', '0004_alter_user_account_tin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_From',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
